on: [push, pull_request, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Copy and commit keymap file'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          mkdir -p ./config/boards/shields/dance/
          cp ./config/dance.keymap ./config/boards/shields/dance/dance.keymap
          git add ./config/boards/shields/dance/dance.keymap
          git commit -m 'chore: copy keymap file'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
  
  build:
    needs: setup
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  
  doc:
      needs: setup
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - run: pip install keymap_drawer
        - name: 'Parse ZMK keymap'
          run: keymap -c ./keymap_img/dance_keymap_config.yaml parse -c 10 -z ./config/boards/shields/dance/dance.keymap --base-keymap ./keymap_img/dance_keymap_base.yaml > ./keymap_img/dance_keymap.yaml
        - name: 'Draw keymap'
          run: keymap -c ./keymap_img/dance_keymap_config.yaml draw --select-layers default num nav fun -k chocofi ./keymap_img/dance_keymap.yaml > ./keymap_img/dance_keymap.svg
        - name: 'Commit keymap image'
          run: |
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add ./keymap_img/dance_keymap.svg
            git commit -m 'doc: update keymap image'
          continue-on-error: true
        - name: 'Push keymap image'
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
