name: Setup

on: [push, pull_request, workflow_dispatch]

jobs:
  copy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: 'Copy keymap file'
        run: |
          mkdir -p ./config/boards/shields/dance/
          cp ./config/dance.keymap ./config/boards/shields/dance/dance.keymap
      - name: 'Commit copied file'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ./config/boards/shields/dance/dance.keymap
          git commit -m 'chore: copy keymap file'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
